// web/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./providers/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      {/* ✅ 폰트 변수 적용(안전): UI 깨짐 없이 일관된 타이포 유지 */}
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}

/*
[변경 요약]
- ✅ body에 Geist 폰트 변수 className 적용(기존 폰트 선언을 실제로 사용)
- ✅ AuthProvider/children 구조는 그대로 유지 (로직 영향 없음)

[수정 전/후 줄수]
- 전: 약 33줄
- 후: 약 35줄

[체크리스트]
- ✅ UI 유지됨 (폰트만 일관 적용, 레이아웃 구조 동일)
- ✅ 인증/세션 로직 변경 없음
*/
